services:
  redis:
    image: redis/redis-stack-server:7.4.0-v8
    command: redis-server /etc/redis/redis.conf
    network_mode: host
    volumes:
      - ./redis.conf:/etc/redis/redis.conf

  backend:
    image: gitlab.polytech.umontpellier.fr:5050/dorian.richard/do-place:1.0.0
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_USER=doplace
      - REDIS_PASSWORD_FILE=/run/secrets/redis
      - FRONTEND_ORIGIN=http://localhost:8081
      - JWT_SECRET_FILE=/run/secrets/jwt
      - HASH_SECRET_FILE=/run/secrets/hash
      - ENABLE_HTTP_COMPRESSION=true
    ports:
      - "8080:80"
    secrets:
      - redis
      - jwt
      - hash

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://localhost:8080/api/v1
    depends_on:
      - backend
    ports:
      - "8081:80"

secrets:
  redis:
    file: ./redis.txt
  jwt:
    file: ./jwt.txt
  hash:
    file: ./hash.txt
